package cli

import (
	"fmt"

	"github.com/spf13/cobra"
)

func newAboutCommand() *cobra.Command {
	return &cobra.Command{
		Use:   "about",
		Short: "Explain what Stockbridge does and how to use it.",
		Long: `Explain what Stockbridge does, what data sources it currently uses,
which commands are available, and what limitations users should understand.`,
		Run: func(cmd *cobra.Command, args []string) {
			fmt.Fprint(cmd.OutOrStdout(), aboutText())
		},
	}
}

func aboutText() string {
	return `Stockbridge
===========

Stockbridge is a CLI tool for producing a sourced fundamental snapshot for a
listed U.S. stock ticker.

What it does today:
  1. Validates the ticker against Nasdaq Trader symbol directory files.
  2. Detects the listing exchange and market.
  3. Maps the ticker to an SEC CIK.
  4. Fetches SEC XBRL company-facts data.
  5. Renders a styled terminal report with fundamentals, notes, sources, and
     retrieval times.

Report presentation:
  - Styled terminal output is the default.
  - Major sections use larger-feeling uppercase headers, borders, spacing, and
    contrast to create hierarchy inside the terminal.
  - Financial values are aligned and color-coded by role: high-signal values,
    cautionary values, risk/negative values, links, notes, and metadata each
    receive distinct styling.
  - The palette is designed to feel informational but energetic: deep blue,
    cyan, green, amber, coral, lavender, and muted gray.
  - Terminals cannot force actual font families or font sizes, so Stockbridge
    uses bold text, spacing, padding, and color to indicate importance.

Available commands:
  stockbridge analyze <ticker>
      Fetch listing and SEC fundamentals for a ticker.

  stockbridge about
      Show this project overview and command guide.

  stockbridge help
      Show command help generated by the CLI.

  stockbridge help analyze
      Show detailed help and flags for the analyze command.

Analyze options:
  --format styled
      Default. Render a styled terminal report with color, section hierarchy,
      emphasized financial values, and a prominent Notes block.

  --format text
      Render plain text output.

  --output, -o <file>
      Write the report to a file. File output is plain text for portability.

Examples:
  stockbridge analyze AMZN
  stockbridge analyze IBM --format text
  stockbridge analyze AMZN --output reports/AMZN.txt

Current limitations:
  - Valuation ratios, interactive charts, and news are not integrated into the
    active CLI report yet.
  - Experimental chart-fetching code is retained for the future desktop/web UI
    but is currently sidelined from the command output.
  - SEC XBRL reporting tags differ across companies, so some metrics may be
    missing or less fresh than others.
  - ETFs, funds, foreign issuers, and unusual securities may not produce a
    useful fundamental report.
  - Output is informational and is not personalized financial advice.
`
}
